"""empty message

Revision ID: 9f9c1cf3fd66
Revises: e1f91343405f
Create Date: 2023-08-01 23:03:04.175747

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = '9f9c1cf3fd66'
down_revision = 'e1f91343405f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_lora', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('data_lora', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_lora', 'updated_at')
    op.drop_column('data_lora', 'created_at')
    # ### end Alembic commands ###
