"""empty message

Revision ID: d70cd620c820
Revises: 9f9c1cf3fd66
Create Date: 2023-08-04 23:50:08.380498

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = 'd70cd620c820'
down_revision = '9f9c1cf3fd66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_lora', sa.Column('RSSI', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_lora', 'RSSI')
    # ### end Alembic commands ###
